### ISSUE TITLE
discrete resource tracking (intro and impl)

### ISSUE THREAD

**Issue by rwcarlsen** [cyclus/fundamentals-paper#10]
Implementation:
- [x] composition deduplication
- [x] decay shortcut
- [x] other nifty things?

Intro:
- [x] resource heritage - kinds of metrics
- [x] resource transactions
- [x] other nifty things?
